
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from multiprocessing import Queue
from datetime import datetime
import queue
import time
import os
import sys

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

canvas = None
window = None
top_20 = []
update_queue = Queue()
command_queue = Queue()
sgf_string = ''

def new_board():
    global top_20, sgf_string
    sgf_string = '(;SZ[19]'
    for i in range(20):
        str = ''
        if i < 10:
            str = '  - '
        else:
            str = ' - '
        canvas.itemconfig(top_20[i], text = 'top ' + f'{i + 1}' + str + '-- , --%')
    return

def show_top5(pos, percent):
    global top_20
    for i in range (20):
        str = ''
        if i < 10:
            str = '  - '
        else:
            str = ' - '
        if percent[i][1][0] > 1:
            canvas.itemconfig(top_20[i], text = 'Top ' + f'{i + 1}' + str + f'{pos[i][0]}' + ', ' + f'{percent[i][1][0]:.2f}' + '%')
        else:
            canvas.itemconfig(top_20[i], text = 'Top ' + f'{i + 1}' + str + '--, --%')
    return

def destroy_window():
    global window
    if update_queue.empty():
        if window is not None:
            window.destroy()
    else:
        update_queue.put((destroy_window, ()))
# def save():
#     update_queue.put((save_file, ()))
def save_file():
    now = datetime.now()
    file_name = str(now).split('.')[0]
    file_name = file_name.replace(' ', '_').replace(':', '_').replace('-', '_') + '.sgf'
    current_dir = sys.path[0]
    dir_path = f'{current_dir}/sgf'
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
    file_path = f'{dir_path}/{file_name}'
    if os.path.isfile(file_path):
        os.remove(file_path)
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(sgf_string + ')')
    # print(f'save {current_dir}')
    file.close()
    return
# save_file()
def top5():
    def update_gui():
        try:
            update_func, args = update_queue.get(block=False)
            update_func(*args)
        except queue.Empty:
            pass
        window.after(100, update_gui)

    global window
    window = Tk()

    window.geometry("360x629")
    window.configure(bg = "#FFFFFF")

    # 獲取螢幕的寬度和高度
    screen_width = window.winfo_screenwidth()
    screen_height = window.winfo_screenheight()

    # 設定視窗的大小
    window_width = 360
    window_height = 629

    # 計算視窗在螢幕上的位置
    x = screen_width - window_width - 10
    y = screen_height - window_height - screen_height // 8
    window.geometry(f"{window_width}x{window_height}+{x}+{y}")
    # 設定視窗在最上層
    window.attributes('-topmost', 1)

    global canvas

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 629,
        width = 360,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        180.0,
        589.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=save_file,
        relief="flat"
    )
    button_1.place(
        x=10.0,
        y=559.0,
        width=340.0,
        height=60.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        180.0,
        274.0,
        image=image_image_2
    )

    canvas.create_text(
        64.5,
        9.0,
        anchor="nw",
        text="Rank - Move, Accuracy",
        fill="#FFFFFF",
        font=("Quantico", 22 * -1)
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        86.0,
        52.0,
        image=image_image_3
    )

    global top_20
    top_20.append(canvas.create_text(
        100,
        41.0,
        anchor="nw",
        text="Top 1   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        86.0,
        79.0,
        image=image_image_4
    )

    top_20.append(canvas.create_text(
        100,
        66.0,
        anchor="nw",
        text="Top 2   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        86.0,
        104.0,
        image=image_image_5
    )

    top_20.append(canvas.create_text(
        100,
        91.0,
        anchor="nw",
        text="Top 3   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_6 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(
        86.0,
        129.0,
        image=image_image_6
    )

    top_20.append(canvas.create_text(
        100,
        116.0,
        anchor="nw",
        text="Top 4   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_7 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_7 = canvas.create_image(
        86.0,
        154.0,
        image=image_image_7
    )

    top_20.append(canvas.create_text(
        100,
        141.0,
        anchor="nw",
        text="Top 5   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_8 = PhotoImage(
        file=relative_to_assets("image_8.png"))
    image_8 = canvas.create_image(
        86.0,
        179.0,
        image=image_image_8
    )

    top_20.append(canvas.create_text(
        100,
        166.0,
        anchor="nw",
        text="Top 6   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_9 = PhotoImage(
        file=relative_to_assets("image_9.png"))
    image_9 = canvas.create_image(
        86.0,
        204.0,
        image=image_image_9
    )

    top_20.append(canvas.create_text(
        100,
        191.0,
        anchor="nw",
        text="Top 7   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_10 = PhotoImage(
        file=relative_to_assets("image_10.png"))
    image_10 = canvas.create_image(
        86.0,
        229.0,
        image=image_image_10
    )

    top_20.append(canvas.create_text(
        100,
        216.0,
        anchor="nw",
        text="Top 8   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_11 = PhotoImage(
        file=relative_to_assets("image_11.png"))
    image_11 = canvas.create_image(
        86.0,
        254.0,
        image=image_image_11
    )

    top_20.append(canvas.create_text(
        100,
        241.0,
        anchor="nw",
        text="Top 9   - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_12 = PhotoImage(
        file=relative_to_assets("image_12.png"))
    image_12 = canvas.create_image(
        86.0,
        279.0,
        image=image_image_12
    )

    top_20.append(canvas.create_text(
        100,
        266.0,
        anchor="nw",
        text="Top 10 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_13 = PhotoImage(
        file=relative_to_assets("image_13.png"))
    image_13 = canvas.create_image(
        86.0,
        304.0,
        image=image_image_13
    )

    top_20.append(canvas.create_text(
        100,
        291.0,
        anchor="nw",
        text="Top 11 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_14 = PhotoImage(
        file=relative_to_assets("image_14.png"))
    image_14 = canvas.create_image(
        86.0,
        329.0,
        image=image_image_14
    )

    top_20.append(canvas.create_text(
        100,
        316.0,
        anchor="nw",
        text="Top 12 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_15 = PhotoImage(
        file=relative_to_assets("image_15.png"))
    image_15 = canvas.create_image(
        86.0,
        354.0,
        image=image_image_15
    )

    top_20.append(canvas.create_text(
        100,
        341.0,
        anchor="nw",
        text="Top 13 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_16 = PhotoImage(
        file=relative_to_assets("image_16.png"))
    image_16 = canvas.create_image(
        86.0,
        379.0,
        image=image_image_16
    )

    top_20.append(canvas.create_text(
        100,
        366.0,
        anchor="nw",
        text="Top 14 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_17 = PhotoImage(
        file=relative_to_assets("image_17.png"))
    image_17 = canvas.create_image(
        86.0,
        404.0,
        image=image_image_17
    )

    top_20.append(canvas.create_text(
        100,
        391.0,
        anchor="nw",
        text="Top 15 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_18 = PhotoImage(
        file=relative_to_assets("image_18.png"))
    image_18 = canvas.create_image(
        86.0,
        429.0,
        image=image_image_18
    )

    top_20.append(canvas.create_text(
        100,
        416.0,
        anchor="nw",
        text="Top 16 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_19 = PhotoImage(
        file=relative_to_assets("image_19.png"))
    image_19 = canvas.create_image(
        86.0,
        454.0,
        image=image_image_19
    )

    top_20.append(canvas.create_text(
        100,
        441.0,
        anchor="nw",
        text="Top 17 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_20 = PhotoImage(
        file=relative_to_assets("image_20.png"))
    image_20 = canvas.create_image(
        86.0,
        479.0,
        image=image_image_20
    )

    top_20.append(canvas.create_text(
        100,
        466.0,
        anchor="nw",
        text="Top 18 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_21 = PhotoImage(
        file=relative_to_assets("image_21.png"))
    image_21 = canvas.create_image(
        86.0,
        504.0,
        image=image_image_21
    )

    top_20.append(canvas.create_text(
        100,
        491.0,
        anchor="nw",
        text="Top 19 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))

    image_image_22 = PhotoImage(
        file=relative_to_assets("image_22.png"))
    image_22 = canvas.create_image(
        86.0,
        529.0,
        image=image_image_22
    )

    top_20.append(canvas.create_text(
        100,
        516.0,
        anchor="nw",
        text="Top 20 - --, --%",
        fill="#FFFFFF",
        font=("Quantico", 18 * -1)
    ))
    window.resizable(False, False)
    window.after(100, update_gui)
    window.mainloop()
